"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import manifest from "@/lib/labs-manifest.json";

/**
 * Tabbed lab-photo gallery, source-of-truth from lib/labs-manifest.json
 * (regenerated by scripts/sync-labs.mjs from the BIPE Drive folder).
 *
 * Pill tabs filter the grid by lab category. When the user selects an
 * empty category, we show a friendly "more photos coming soon" notice
 * rather than an empty grid.
 *
 * Cloudinary handles the resizing — we ship one URL per asset and rely
 * on f_auto / q_auto / c_fill transforms for the thumbnail variants.
 */

const CLOUD = "dg8sty5ej";

type LabPhoto = (typeof manifest)[number];

const CATEGORIES: { id: string; label: string }[] = [
  { id: "all",        label: "All" },
  { id: "cse",        label: "Computer Science" },
  { id: "ee",         label: "Electrical & Electronics" },
  { id: "mechanical", label: "Mechanical" },
  { id: "civil",      label: "Civil" },
];

function thumbUrl(p: LabPhoto): string {
  // 4:5 portrait crop, sized for the grid (CDN auto-picks DPR/format).
  return `https://res.cloudinary.com/${CLOUD}/image/upload/f_auto,q_auto,w_640,h_800,c_fill,g_auto/v${p.version}/${p.publicId}`;
}

function fullUrl(p: LabPhoto): string {
  // Larger asset for the lightbox / future modal.
  return `https://res.cloudinary.com/${CLOUD}/image/upload/f_auto,q_auto,w_1600/v${p.version}/${p.publicId}`;
}

export function LabsGallery() {
  const [active, setActive] = useState<string>("all");

  const counts = useMemo(() => {
    const out: Record<string, number> = { all: manifest.length };
    for (const p of manifest as LabPhoto[]) {
      out[p.category] = (out[p.category] ?? 0) + 1;
    }
    return out;
  }, []);

  const items = useMemo<LabPhoto[]>(() => {
    if (active === "all") return manifest as LabPhoto[];
    return (manifest as LabPhoto[]).filter((p) => p.category === active);
  }, [active]);

  return (
    <div>
      {/* Pill tabs */}
      <div className="bipe-labs-pills" role="tablist" aria-label="Filter labs by department">
        {CATEGORIES.map((c) => {
          const n = counts[c.id] ?? 0;
          const on = active === c.id;
          const empty = n === 0 && c.id !== "all";
          return (
            <button
              key={c.id}
              role="tab"
              aria-selected={on}
              aria-controls="bipe-labs-grid"
              type="button"
              onClick={() => setActive(c.id)}
              className={
                "bipe-labs-pill" +
                (on ? " is-on" : "") +
                (empty ? " is-empty" : "")
              }
              disabled={empty}
              title={empty ? "Photos coming soon" : `${n} ${n === 1 ? "photo" : "photos"}`}
            >
              {c.label}
              <span className="bipe-labs-pill-count">{n}</span>
            </button>
          );
        })}
      </div>

      {/* Grid */}
      <div id="bipe-labs-grid" role="tabpanel" key={active}>
        {items.length === 0 ? (
          <div className="bipe-labs-empty">
            <div
              className="serif"
              style={{ fontStyle: "italic", fontSize: 32, color: "var(--brand)" }}
            >
              More photos coming soon.
            </div>
            <p style={{ marginTop: 10, color: "var(--ink-3)", fontSize: 14 }}>
              We&rsquo;re shooting this department next. Check back in a few weeks
              or visit campus to see it first-hand.
            </p>
          </div>
        ) : (
          <div className="bipe-labs-grid">
            {items.map((p) => (
              <figure key={p.publicId} className="bipe-lab-tile">
                <a
                  href={fullUrl(p)}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`Open ${p.title} full-size`}
                  style={{ display: "block", aspectRatio: "4 / 5", position: "relative", background: "var(--paper-2)" }}
                >
                  <Image
                    src={thumbUrl(p)}
                    alt={p.title}
                    fill
                    sizes="(max-width: 640px) 50vw, (max-width: 980px) 33vw, 25vw"
                    style={{ objectFit: "cover" }}
                  />
                </a>
                <figcaption className="bipe-lab-cap">
                  <span className="bipe-lab-cap-title">{p.title}</span>
                  <span className="bipe-lab-cap-meta">
                    {labelFor(p.category)}
                  </span>
                </figcaption>
              </figure>
            ))}
          </div>
        )}
      </div>

      <p
        style={{
          marginTop: 28,
          fontSize: 13,
          color: "var(--ink-3)",
          fontFamily: "var(--font-mono)",
          letterSpacing: "0.06em",
          textTransform: "uppercase",
          textAlign: "center",
        }}
      >
        {manifest.length} photos · BIPE Varanasi
      </p>
    </div>
  );
}

function labelFor(id: string): string {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}
