"use client";

import { useEffect, useMemo, useState } from "react";
import manifest from "@/lib/labs-manifest.json";
import { LabsLightbox, type LabsLightboxPhoto } from "./LabsLightbox";

/**
 * Tabbed lab-photo gallery, source-of-truth from lib/labs-manifest.json
 * (regenerated by scripts/sync-labs.mjs from the BIPE Drive folder).
 *
 * Pill tabs filter the grid by lab category. The grid renders
 * PAGE_SIZE tiles at a time (4×4 on desktop) with a "Show more" button
 * to reveal the next batch — keeps the initial paint quick on
 * categories with dozens of photos. Tab switch resets the visible
 * count back to PAGE_SIZE.
 *
 * Clicking a tile opens the lightbox seeded with the FILTERED list,
 * so left/right navigation stays scoped to the active department.
 */

const CLOUD = "dg8sty5ej";
const PAGE_SIZE = 16;

type LabPhoto = (typeof manifest)[number];

const CATEGORIES: { id: string; label: string }[] = [
  { id: "all",        label: "All" },
  { id: "cse",        label: "Computer Science" },
  { id: "ee",         label: "Electrical & Electronics" },
  { id: "mechanical", label: "Mechanical" },
  { id: "civil",      label: "Civil" },
];

function thumbUrl(p: LabPhoto): string {
  return `https://res.cloudinary.com/${CLOUD}/image/upload/f_auto,q_auto,w_640,h_800,c_fill,g_auto/v${p.version}/${p.publicId}`;
}

function fullUrl(p: LabPhoto): string {
  return `https://res.cloudinary.com/${CLOUD}/image/upload/f_auto,q_auto,w_1600/v${p.version}/${p.publicId}`;
}

function labelFor(id: string): string {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}

export function LabsGallery() {
  const [active, setActive] = useState<string>("all");
  const [visible, setVisible] = useState<number>(PAGE_SIZE);
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null);

  const counts = useMemo(() => {
    const out: Record<string, number> = { all: manifest.length };
    for (const p of manifest as LabPhoto[]) {
      out[p.category] = (out[p.category] ?? 0) + 1;
    }
    return out;
  }, []);

  const items = useMemo<LabPhoto[]>(() => {
    if (active === "all") return manifest as LabPhoto[];
    return (manifest as LabPhoto[]).filter((p) => p.category === active);
  }, [active]);

  // Reset paging window each time the user picks a different tab — they
  // expect "show me the start of THIS category", not the leftover offset
  // from the previous filter.
  const [lastActive, setLastActive] = useState(active);
  if (active !== lastActive) {
    setLastActive(active);
    setVisible(PAGE_SIZE);
  }

  // Photos passed to the lightbox are the full filtered list, so left/
  // right navigation isn't truncated by the visible window.
  const lightboxPhotos: LabsLightboxPhoto[] = useMemo(
    () =>
      items.map((p) => ({
        src: fullUrl(p),
        title: p.title,
        categoryLabel: labelFor(p.category),
        width: p.width,
        height: p.height,
      })),
    [items],
  );

  const shown = items.slice(0, visible);
  const remaining = Math.max(0, items.length - visible);

  return (
    <div>
      {/* Pill tabs */}
      <div className="bipe-labs-pills" role="tablist" aria-label="Filter labs by department">
        {CATEGORIES.map((c) => {
          const n = counts[c.id] ?? 0;
          const on = active === c.id;
          const empty = n === 0 && c.id !== "all";
          return (
            <button
              key={c.id}
              role="tab"
              aria-selected={on}
              aria-controls="bipe-labs-grid"
              type="button"
              onClick={() => setActive(c.id)}
              className={
                "bipe-labs-pill" +
                (on ? " is-on" : "") +
                (empty ? " is-empty" : "")
              }
              disabled={empty}
              title={empty ? "Photos coming soon" : `${n} ${n === 1 ? "photo" : "photos"}`}
            >
              {c.label}
              <span className="bipe-labs-pill-count">{n}</span>
            </button>
          );
        })}
      </div>

      {/* Grid */}
      <div id="bipe-labs-grid" role="tabpanel" key={active}>
        {items.length === 0 ? (
          <div className="bipe-labs-empty">
            <div className="serif" style={{ fontStyle: "italic", fontSize: 32, color: "var(--brand)" }}>
              More photos coming soon.
            </div>
            <p style={{ marginTop: 10, color: "var(--ink-3)", fontSize: 14 }}>
              We&rsquo;re shooting this department next. Check back in a few weeks
              or visit campus to see it first-hand.
            </p>
          </div>
        ) : (
          <>
            <div className="bipe-labs-grid">
              {shown.map((p, i) => (
                <figure key={p.publicId} className="bipe-lab-tile">
                  <button
                    type="button"
                    onClick={() => setLightboxIndex(i)}
                    aria-label={`Open ${p.title}`}
                    className="bipe-lab-tile-trigger"
                    style={{ aspectRatio: "4 / 5" }}
                  >
                    {/* Plain <img> — Cloudinary already returns
                        WebP/AVIF via f_auto and the right size via
                        w_/h_, so going through Next's optimiser was
                        breaking on these URLs. */}
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={thumbUrl(p)}
                      alt={p.title}
                      loading="lazy"
                      decoding="async"
                      style={{
                        position: "absolute",
                        inset: 0,
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                      }}
                    />
                    <span aria-hidden="true" className="bipe-lab-tile-glass" />
                  </button>
                  <figcaption className="bipe-lab-cap">
                    <span className="bipe-lab-cap-title">{p.title}</span>
                    <span className="bipe-lab-cap-meta">{labelFor(p.category)}</span>
                  </figcaption>
                </figure>
              ))}
            </div>

            {/* Show more — only when there are still hidden tiles in the
                current filter. Reveals one more page of PAGE_SIZE. */}
            {remaining > 0 && (
              <div className="bipe-labs-more">
                <button
                  type="button"
                  className="btn btn-ghost"
                  onClick={() => setVisible((v) => v + PAGE_SIZE)}
                >
                  Show {Math.min(remaining, PAGE_SIZE)} more
                  <span className="bipe-labs-more-count">
                    +{remaining}
                  </span>
                </button>
              </div>
            )}
          </>
        )}
      </div>

      <p
        style={{
          marginTop: 28,
          fontSize: 13,
          color: "var(--ink-3)",
          fontFamily: "var(--font-mono)",
          letterSpacing: "0.06em",
          textTransform: "uppercase",
          textAlign: "center",
        }}
      >
        {manifest.length} photos · BIPE Varanasi
      </p>

      <LabsLightbox
        photos={lightboxPhotos}
        index={lightboxIndex}
        onClose={() => setLightboxIndex(null)}
        onChange={setLightboxIndex}
      />
    </div>
  );
}
